### ISSUE TITLE
Clone command is wrong.

### ISSUE THREAD

**Issue by Drup** [Somasis/shiki-colors-revival#1]
The command `git clone https://github.com/Somasis/shiki-colors-revival` in the readme should contain the argument `--recursive`, otherwise it doesn't work.

**Comment by somasis** [comment]
Fixed. Added a check for the existence of zuki-theme's git folder, so that make-colors-themes does it when generating. I think that is a better way than just depending on people cloning correctly.

**Comment by Drup** [comment]
Agreed. Thanks for all the fixes. :)
