### ISSUE TITLE
Checkboxes don't show in Firefox

### ISSUE THREAD

**Issue by Gallandaluz** [Somasis/shiki-colors-revival#12]
Firefox 48 finally includes a fix allowing checkboxes to show using GTK 3.20. They are indeed visible using the latest Numix theme, but there are still issues with the Shiki Revival and Classic themes.

**Comment by somasis** [comment]
This project is now abandoned, I don't have the know-how to maintain this theme in order to cope with GTK developers constantly breaking things. Sorry.
