### ISSUE TITLE
"No such file or directory" error when running make

### ISSUE THREAD

**Issue by Lesik** [Somasis/shiki-colors-revival#5]
First of all, I am very happy this exists. I want my GNOME 2 desktop back, but all programs start switching to GTK3 and look very ugly.
I am trying to `make` this on latest Arch Linux.

``` sh
[[ "" ]] || git submodule update
cd numix-themes && rm -rf xfwm4 metacity-1 openbox-3 xfce-notify-4.0 index.theme
make Shiki-Brave; make Shiki-Human; make Shiki-Illustrious; make Shiki-Noble; make Shiki-Wine; make Shiki-Wise;
make[1]: Entering directory '/home/user/shiki-colors-revival'
Generating Shiki-Brave from numix-themes...
cp -r numix-themes Shiki-Brave
sed -i  Shiki-Brave/gtk-2.0/gtkrc Shiki-Brave/gtk-3.0/*.css Shiki-Brave/gtk-3.0/assets/*.svg \
        Shiki-Brave/gtk-3.0/apps/*.css           \
    -e 's/#d64937/#729fcf/g'    \
    -e 's/#2d2d2d/#212121/g'
sed: can't read Shiki-Brave/gtk-2.0/gtkrc: No such file or directory
sed: can't read Shiki-Brave/gtk-3.0/*.css: No such file or directory
sed: can't read Shiki-Brave/gtk-3.0/assets/*.svg: No such file or directory
sed: can't read Shiki-Brave/gtk-3.0/apps/*.css: No such file or directory
Makefile:54: recipe for target 'Shiki-Brave' failed
make[1]: *** [Shiki-Brave] Error 2
make[1]: Leaving directory '/home/user/shiki-colors-revival'
```

And this happens for every variation of the theme.

`sed` version 4.2.2
`make` version 4.1
`git` version 2.4.2
`gtk-engine-murrine` version 0.98.2

**Comment by Lesik** [comment]
Sorry about the title, I accidentally submitted this issue before I finished writing.

**Comment by Lesik** [comment]
So the issue is that numix-themes is empty after cloning, then it copies the contents of numix-themes, then it tries to change them but since they're gone it fails.
I just wonder why it doesn't download numix-themes automatically. I got the folder from Github manually and (obviously) it works again.

**Comment by somasis** [comment]
I didn't test the `git submodule` stuff enough, it wasn't doing `git submodule init` like it needs to do before updating. Try the latest revision (725bdb2d7d757c8fff75e0e8a55fb6698dc069b6), please?

**Comment by Lesik** [comment]
Yes, seems to work now.

I may be mistaken, but I think that `make` usually does not issue `make install` automatically. `make` should be run with normal user privileges, while `make install` as root. In `shiki-colors-revival` when I run `make` it complains about having no rights to write to /usr/share. I think the writing should be only part of `make install`.

**Comment by somasis** [comment]
Good, and yes you're right. That's fixed too, now.
