### ISSUE TITLE
Menubar color does not match Shiki metacity/xfwm theme

### ISSUE THREAD

**Issue by Lesik** [Somasis/shiki-colors-revival#6]
![screenshot](https://cloud.githubusercontent.com/assets/2021487/8024754/c6baccd4-0d3e-11e5-8aa5-8af04d9b4da9.png)
Could you ajust the GTK theme's menubar color to fit Shiki?

**Comment by somasis** [comment]
You need to use Shiki-Colors-Xfwm, that's actually an intentional color change. If you're using metacity/whatever though, I'd be willing to accept a pull request which updates it for the new theme (based off the Xfwm4 theme's graphics, perhaps?)

**Comment by Lesik** [comment]
I may find time to check how metacity theming works later. Need this theme to work in MATE.
But I think it'd be easier (and more aesthetically pleasing) to just make a compiler option `--lighter-menubars` which then generates the theme with a lighter menubar to fit Shiki.

**Comment by somasis** [comment]
Never mind, I'm actually working on this now. Splitting the dark colors into Shiki-<color>-Revival, and original colors will be Shiki-<color>-Classic. Also getting metacity looking right.

**Comment by somasis** [comment]
Ok, it should be fixed now (bc20f24). Shiki-Classic is now a version of the themes meant to look like the original themes without my modifications. There's also now metacity themes for all the different themes.

**Comment by Lesik** [comment]
Good job. I wonder why you've choosen the square-y themes for metacity?

**Comment by somasis** [comment]
Numix is squared and so it fits in with the rest of the theme more.
