### ISSUE TITLE
Shiki-Dust

### ISSUE THREAD

**Issue by Gallandaluz** [Somasis/shiki-colors-revival#8]
Is it planned to also revive Shiki-Dust? That's the one i'm actually looking for in the series.

**Comment by somasis** [comment]
I did plan to do it originally but I neglected to do it since it'd require some more graphics to be made and at the time of starting the project, the build system wasn't really good enough for it.

I will look at it over the weekend, it should be easier now.

**Comment by Gallandaluz** [comment]
Thanks, i'll be waiting.
