### ISSUE TITLE
Broken in GTK3 applications since GTK3's update to 3.20

### ISSUE THREAD

**Issue by aphirst** [Somasis/shiki-colors-revival#9]
As mentioned [here](https://bbs.archlinux.org/viewtopic.php?id=210815) and other places, some themes were affected by GTK3's recent update. As far as I can see on my machine (Arch x86_64), this is one of them.

I can post any other information that might be useful, feel free to ask. I'll also try to see if I can work out something else to post.

**Comment by somasis** [comment]
Yeah, I've noticed. I think it might be an issue with upstream though, I'm keeping an eye on them to see if anything related to gtk appears soon.

**Comment by somasis** [comment]
Oh, actually I just checked upstream and I saw some commits for gtk 3.20 :) I'll see about upgrading it today and tagging a new release.

**Comment by somasis** [comment]
...anyway, so it turns out that numix 3.20 still seems a bit beta with 3.20. I'll push some build system changes I made when working on 3.20 stuff (we need to use Numix's build system to build the scss files) but I'm going to wait to put out a new release, until it's a little more finished on their end.

**Comment by Hafler** [comment]
Any new update on this? I tried out the Numix build earlier today with little to no issues, but Shiki-Colors-Revival still is. Any new information would be much appreciated. :+1:

**Comment by somasis** [comment]
Okay, I managed to get it working decently in ba915d3. There's still a few issues, though; checkboxes in menus look a little weird (not sure if that's an upstream thing or not), and GTK 3 applets on my Xfce panel look too dark as well...

![screenshot_2016-04-29_23-44-36](https://cloud.githubusercontent.com/assets/264788/14933660/59841af8-0e64-11e6-84f5-69f6fef7ecf3.png)

**Comment by somasis** [comment]
This project is now abandoned, I don't have the know-how to maintain this theme in order to cope with GTK developers constantly breaking things. Sorry.

**Comment by Lesik** [comment]
@somasis It seems like the GTK theming API is now pretty much stable, do you think you will maybe pick this up again? We love Shiki!
